name: Generate WARP+ Key
on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Key Script
        run: |
          cat << 'EOF' > warp.py
          import requests, random, string, time
          def gen():
              install_id = ''.join(random.choices(string.ascii_letters + string.digits, k=22))
              body = {"key": f"{''.join(random.choices(string.ascii_letters + string.digits, k=43))}=",
                      "install_id": install_id,
                      "fcm_token": f"{install_id}:APA91b{ ''.join(random.choices(string.ascii_letters + string.digits, k=134)) }",
                      "referrer": "31p56DqI-V279l6sL-7m48aW2I",
                      "warp_enabled": False, "tos": "2020-04-01T00:00:00.000+02:00", "type": "Android", "locale": "en_US"}
              headers = {"Content-Type": "application/json; charset=UTF-8", "Host": "api.cloudflareclient.com", "User-Agent": "okhttp/3.12.1"}
              try:
                  r = requests.post("https://api.cloudflareclient.com/v0a1922/reg", json=body, headers=headers)
                  if r.status_code == 200:
                      print(f"Generated WARP+ Key: {r.json()['referrer']}")
                  else:
                      print("Error: Could not generate key. Status code:", r.status_code)
              except Exception as e:
                  print(f"Error: {e}")
          gen()
          EOF
      - name: Run Generator
        run: |
          pip install requests
          python3 warp.py
