name: Generate WARP+ Key
on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Generator
        run: |
          # Script ကို အသစ်ပြန်ဆွဲပြီး တိုက်ရိုက် run တာပါ
          curl -sL https://raw.githubusercontent.com/aliirsyaad/warp-plus-generator/main/warp.py -o warp.py
          python3 warp.py
